name: deploy on heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      database:
        image: postgres
         - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: senha@01
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Running test
        run: npm i && npm run test
      - name:
        run: npm i && npm run build
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "main"
        env:
          DATABASE_URL: ${{secrets.DATABASE_URL}}